"""Added Reviews Model

Revision ID: 3fc6f6532580
Revises: 2eaf1d236d23
Create Date: 2024-02-14 10:48:54.449590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc6f6532580'
down_revision = '2eaf1d236d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
